version: '3'

services:
  web:
    container_name: webserver
    image: php-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/usr/share/nginx/html
      - /Users/jithesh/Projects/ssl-certs/localhost.pem:/etc/ssl/certs/localhost.pem
      - /Users/jithesh/Projects/ssl-certs/localhost-key.pem:/etc/ssl/private/localhost-key.pem
  mysql:
    container_name: mysql8
    #image: mysql:8.0
    image: mysql/mysql-server:latest #better apple silicon stability: https://hub.docker.com/r/mysql/mysql-server
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root@6719
  redis:
    image: redis
    container_name: cache
    command: redis-server --requirepass redispass
    ports:
      - "6379:6379"